### ISSUE TITLE
Not working on servers

### ISSUE THREAD

**Issue by Rosenblack** [CmdrJane/music-box#1]
![image](https://user-images.githubusercontent.com/10399357/162865912-379f76d0-cfc6-4a66-af93-9b0e65c721e6.png)
just as the title says, the mod states it needs to be both client and server but crashes the server when trying to boot, despite working in singleplayer

**Comment by CmdrJane** [comment]
Please provide full log and minecraft version

**Comment by Rosenblack** [comment]
mc 1.18.2 fabric 0.13.13 

[latest.log](https://github.com/CmdrJane/music-box/files/8495075/latest.log)

**Comment by CmdrJane** [comment]
fixed in latest release
